module.exports = {
  okapi: {
    'url': 'https://kong-folio-dev.stanford.edu',
    'uiUrl': 'https://folio-dev.stanford.edu',
    'authnUrl': 'https://keycloak-folio-dev.stanford.edu'
  },
  config: {
    hasAllPerms: true,
    useSecureTokens: true,
    logCategories: 'core,path,action,xhr',
    logPrefix: '--',
    maxUnpagedResourceCount: 2000,
    showPerms: true,
    isSingleTenant: true,
    isEureka: true,
    tenantOptions: {sul: {name: "sul", clientId: "sul-application"}},
    enableEcsRequests: false,
    idleSessionWarningSeconds: 60,
    maxUnpagedResourceCount: 2000,
    aboutInstallDate: "2025-10-28",
    aboutInstallMessage: "Eureka Dev Sunflower CSP 4",
    rtr: {
      idleSessionTTL: '1h',
      idleModalTTL: '30s',
    }
  },
  modules: {
    '@folio/acquisition-units': {},
    '@folio/agreements': {},
    '@folio/authorization-policies': {},
    '@folio/authorization-roles': {},
    '@folio/bulk-edit': {},
    '@folio/calendar' : {},
    '@folio/checkin' : {},
    '@folio/checkout' : {},
    '@folio/circulation' : {},
    '@folio/circulation-log' : {},
    '@folio/claims': {},
    '@folio/courses' : {},
    '@folio/dashboard': {},
    '@folio/data-export' : {},
    '@folio/data-import' : {},
    '@folio/developer' : {},
    '@folio/eholdings' : {},
    '@folio/erm-comparisons': {},
    '@folio/erm-usage': {},
    '@folio/export-manager': {},
    '@folio/finance' : {},
    '@folio/gobi-settings': {},
    '@folio/handler-stripes-registry': {},
    '@folio/inventory' : {},
    '@folio/invoice': {},
    '@folio/ld-folio-wrapper': {},
    '@folio/ldp': {},
    '@folio/licenses': {},
    '@folio/lists': {},
    '@folio/local-kb-admin': {},
    '@folio/marc-authorities': {},
    '@folio/myprofile' : {},
    '@folio/notes' : {},
    '@folio/oai-pmh' : {},
    '@folio/orders': {},
    '@folio/organizations' : {},
    '@folio/plugin-bursar-export': {},
    '@folio/plugin-create-inventory-records' : {},
    '@folio/plugin-eusage-reports': {},
    '@folio/plugin-find-agreement': {},
    '@folio/plugin-find-authority' : {},
    '@folio/plugin-find-contact': {},
    '@folio/plugin-find-eresource': {},
    '@folio/plugin-find-erm-usage-data-provider': {},
    '@folio/plugin-find-fund': {},
    '@folio/plugin-find-import-profile' : {},
    '@folio/plugin-find-instance' : {},
    '@folio/plugin-find-interface' : {},
    '@folio/plugin-find-license': {},
    '@folio/plugin-find-organization': {},
    '@folio/plugin-find-package-title': {},
    '@folio/plugin-find-po-line': {},
    '@folio/plugin-find-user' : {},
    '@folio/plugin-query-builder': {},
    '@folio/plugin-select-application' : {},
    '@folio/quick-marc': {},
    '@folio/reading-room' : {},
    '@folio/receiving' : {},
    '@folio/remote-storage' : {},
    '@folio/requests' : {},
    '@folio/serials-management' : {},
    '@folio/service-interaction': {},
    '@folio/servicepoints' : {},
    '@folio/stripes-acq-components' : {},
    '@folio/stripes-authority-components' : {},
    '@folio/stripes-erm-components' : {},
    '@folio/stripes-inventory-components' : {},
    '@folio/stripes-marc-components' : {},
    '@folio/tags': {},
    '@folio/tenant-settings' : {},
    '@folio/users' : {},
  },
  branding: {
    logo: {
      src: './tenant-assets/SUSig_2color_Stree_StnfrdOnly_Left.png',
      alt: 'Stanford University',
    },
    favicon: {
      src: './tenant-assets/stanford-favicon.png',
    },
  }
};